# Generated by Django 5.2.3 on 2026-06-06 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.EmailField(default='team@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='role',
            field=models.CharField(default='Employee', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='skill',
            field=models.CharField(default='Developer', max_length=100),
            preserve_default=False,
        ),
    ]
