# Generated by Django 5.2.3 on 2026-06-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0003_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='agenda',
            new_name='description',
        ),
    ]
